name: ipyvolume-rtd
channels:
  - conda-forge
dependencies:
  - nss  # [linux] required for chromium
  - alsa-lib  # [linux] required for chromium
  - nodejs
  - jupyter_sphinx >=0.1.4
  - ipywidgets >=7.4.0
  - traittypes
  - traitlets
  - Pillow
  - scipy
  - nbsphinx
  - recommonmark
  - matplotlib
  - ipywebrtc
  - requests
  - numpy >= 1.14
  # - pip:
  #   - ipyvolume ==0.5.1
  #   - https://github.com/maartenbreddels/sphinx-gallery/archive/notebook_executor.zip
  #   - PyChromeDevTools
